name: AFL

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
       

permissions:
  contents: read



jobs:
  AFL-Fuzzer:
    runs-on: ubuntu-latest
    env: 
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
    
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: |
          make
          cd llvm_mode
          sudo apt-get install -y clang llvm-dev
          set $LLVM_CONFIG=llvm-config-3.5
          sudo make
          cd ..
          sudo make install
          
        
      - name: AFL Build
        run: |
          
          AFL_HARDEN=1 ./afl-gcc -fsanitize=address ReadFile/imgRead_Fuzzer.c -o ReadFile/imgRead_Fuzzer
          echo imgRead_Fuzzer >ReadFile/imgRead_Fuzzer
          
      - name: AFL Processing Image
        run: |
          cd ReadFile/input
          xxd image.img
          cd ..
           
      - name: AFL Run
        run: afl-fuzz -i ReadFile/input/ -o ReadFile/output -m none -- ./ReadFile/imgRead_Fuzzer @@
