language: c

env:
  - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_NO_UI=1 AFL_STOP_MANUALLY=1
  - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_NO_UI=1 AFL_EXIT_WHEN_DONE=1
 # TODO: test AFL_BENCH_UNTIL_CRASH once we have a target that crashes
  - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_NO_UI=1 AFL_BENCH_JUST_ONE=1

before_install:
  - sudo apt-get install -y clang llvm-dev

# TODO: Look into splitting off some builds using a build matrix.
# TODO: Move this all into a bash script so we don't need to write bash in yaml.
script:
  - sudo make
  - cd ReadFile
  - AFL_HARDEN=1 afl-gcc -fsanitize=address -fsanitize=undefined imgRead_Fuzzer.c -o imgRead_fuzzer
  - cd input
  - cat image.img
  - hexyl image.img
  - cd ..
  - afl-fuzz -i input/ -o output -- ./imgRead_Fuzzer @@
  - afl-fuzz -i input/ -o output -m none -- ./imgRead_Fuzzer @@
