name: AFL

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
       

permissions:
  contents: read


jobs:
  AFL-Fuzzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: |
          make
          cd llvm_mode
          make
          cd ..
          cd AFL
          make install
        
      - name: AFL Build
        run: |
          cd AFL/ReadFile
          AFL_HARDEN=1 afl-gcc -fsanitize=address -fsanitize=undefined imgRead_Fuzzer.c -o imgRead_fuzzer
          
      - name: AFL Processing Image
        run: |
          cd AFL/ReadFile/input
          hexyl image.img
          cd ..
          
      - name: AFL Run
        run: |
          cd AFL/ReadFile
          afl-fuzz -i input/ -o output -m none -- ./imgRead_Fuzzer @@
