name: AFL

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
       

permissions:
  contents: read


jobs:
  AFL-Fuzzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installaing Depencies
        run: sudo apt-get install -y clang llvm-dev
        
      - name: AFL Build
        run: |
          sudo make
          cd ReadFile
          AFL_HARDEN=1 afl-gcc -fsanitize=address -fsanitize=undefined imgRead_Fuzzer.c -o imgRead_fuzzer
      - name: AFL image Build
        run: |
          cd input
          cat image.img
          hexyl image.img
          cd ..
      - name: AFL Run
        run: |
          afl-fuzz -i input/ -o output -- ./imgRead_Fuzzer @@
          afl-fuzz -i input/ -o output -m none -- ./imgRead_Fuzzer @@
